import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Ostad Blog Application",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="navbar bg-gray-900 p-1 text-white flex justify-end">
                    <Navbar></Navbar>
                </div>
                <main className="m-4">{children}</main>
                <Footer></Footer>
            </body>
        </html>
    );
}
